# Generated by Django 5.2.1 on 2025-05-21 02:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('boards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['order', 'id'], 'verbose_name': '板块', 'verbose_name_plural': '板块'},
        ),
        migrations.AddField(
            model_name='board',
            name='access_type',
            field=models.CharField(choices=[('public', '公开'), ('registered', '仅注册用户'), ('groups', '指定用户组'), ('users', '指定用户')], default='public', max_length=20, verbose_name='访问权限类型'),
        ),
        migrations.AddField(
            model_name='board',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, related_name='accessible_boards', to='auth.group', verbose_name='允许访问的用户组'),
        ),
        migrations.AddField(
            model_name='board',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='accessible_boards', to=settings.AUTH_USER_MODEL, verbose_name='允许访问的用户'),
        ),
        migrations.AddField(
            model_name='board',
            name='order',
            field=models.IntegerField(default=0, help_text='数字越小排序越靠前', verbose_name='排序顺序'),
        ),
    ]
