# Generated by Django 5.2.1 on 2025-06-15 18:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("comment", "评论通知"),
                            ("reply", "回复通知"),
                            ("like", "点赞通知"),
                            ("system", "系统通知"),
                        ],
                        max_length=20,
                        verbose_name="通知类型",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="通知标题")),
                ("content", models.TextField(verbose_name="通知内容")),
                (
                    "target_type",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="目标类型"
                    ),
                ),
                (
                    "target_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="目标ID"
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="是否已读"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="发送用户",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="接收用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "消息通知",
                "verbose_name_plural": "消息通知",
                "db_table": "notifications",
                "ordering": ["-created_at"],
            },
        ),
    ]
