# Generated by Django 5.2.1 on 2025-06-15 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_alter_like_model"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="like",
            new_name="likes_content_4ba168_idx",
            old_name="likes_content_idx",
        ),
    ]
